name: tests

on:
  workflow_dispatch: # allows manual triggering
  push:
    paths-ignore:
      - "**.md"
      - "docs/**"
      - ".github/**"
    branches:
      - main
  pull_request:
    paths-ignore:
      - "**.md"
      - "docs/**"
      - ".github/**"

jobs:
  ci-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: DeterminateSystems/nix-installer-action@main

      - name: Clojure tests
        run: |
          nix develop --command kaocha

      - name: Integration tests
        run: |
          nix develop --command bats --timing test
          echo "Derivations:"
          cat "/tmp/.cljnix-derivations"
