name: tests

on:
  push:
    paths-ignore:
      - "**.md"
      - "docs/**"
    branches:
      - master
  pull_request:
    paths-ignore:
      - "**.md"
      - "docs/**"
    branches:
      - master

jobs:
  update-nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v19
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Install Cachix
        uses: cachix/cachix-action@v12
        with:
          name: clj-nix-ci
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Clojure tests
        run: |
          nix shell .#devShells.x86_64-linux.default --command kaocha
